"""
Botragram

Description:
    Trading signal generation engine.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Standard Library
# =============================================================================
from collections.abc import Sequence
from dataclasses import dataclass, replace
from decimal import Decimal

# =============================================================================
# Local Imports
# =============================================================================
from botragram.enums import SignalType, StrategyType
from botragram.models import Candle, Signal
from botragram.strategies.factory import StrategyResolver

__all__ = [
    "SignalEngine",
    "has_account_ratio_evaluation",
    "has_funding_evaluation",
    "has_oi_evaluation",
]


# =============================================================================
# Helper Functions
# =============================================================================
def has_oi_evaluation(reason: str | None) -> bool:
    """Return whether Open Interest analysis was already applied to signal reason."""
    if not reason:
        return False
    return (
        "[REJECTED_OI]" in reason
        or "[OI_CONFLUENCE]" in reason
        or "[OI:" in reason
        or "[Bullish Long Buildup" in reason
        or "[Transient Long Buildup" in reason
        or "[Warning: Short Covering" in reason
        or "[Contradictory Short Buildup" in reason
        or "[Warning: Long Liquidation" in reason
        or "[Bearish Short Buildup" in reason
        or "[Transient Short Buildup" in reason
        or "[Contradictory Long Buildup" in reason
        or "Short Covering squeeze" in reason
        or "Long Liquidation flush" in reason
    )


def has_funding_evaluation(reason: str | None) -> bool:
    """Return whether Funding sentiment filter was already applied to signal reason."""
    if not reason:
        return False
    return (
        "[REJECTED_FUNDING_CROWDED]" in reason
        or "[CROWDED_LONG: funding" in reason
        or "[CROWDED_SHORT: funding" in reason
    )


def has_account_ratio_evaluation(reason: str | None) -> bool:
    """Return whether Account L/S Ratio filter was already applied to signal reason."""
    if not reason:
        return False
    return (
        "[REJECTED_LS_RATIO]" in reason
        or "crowded long)" in reason
        or "crowded short)" in reason
        or "Top Trader L/S" in reason
        or "Account L/S" in reason
        or "Global L/S" in reason
    )


# =============================================================================
# Signal Engine
# =============================================================================
@dataclass(slots=True, kw_only=True, frozen=True)
class SignalEngine:
    """Generate signals from an explicit type resolved by an immutable registry."""

    strategy_resolver: StrategyResolver
    default_strategy_type: StrategyType
    invert_signals: bool = False
    use_open_interest: bool = False
    min_oi_change_pct: Decimal = Decimal("0.0")
    oi_confidence_bonus: Decimal = Decimal("0.05")
    require_oi_confluence: bool = False
    filter_funding_sentiment: bool = False
    max_long_funding_rate: Decimal = Decimal("0.0005")
    min_short_funding_rate: Decimal = Decimal("-0.0005")
    require_funding_sentiment: bool = True
    filter_account_ratio: bool = False
    max_long_account_ratio: Decimal = Decimal("0.75")
    min_short_account_ratio: Decimal = Decimal("0.25")
    require_account_ratio_confluence: bool = True
    confirm_htf_account_ratio: bool = False

    def generate(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate a trading signal from market candles.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit strategy selection. Omitted only by legacy
                non-context callers, which use the immutable configured default.

        Returns:
            Signal generated by the resolved strategy, optionally inverted.

        Raises:
            ValueError: If candle data is invalid or insufficient.
        """
        resolved_strategy_type = (
            strategy_type if strategy_type is not None else self.default_strategy_type
        )
        strategy = self.strategy_resolver.resolve(
            strategy_type=resolved_strategy_type,
        )
        signal = strategy.generate_signal(
            candles=candles,
        )

        if self.invert_signals:
            if signal.signal_type is SignalType.BUY:
                signal = replace(
                    signal,
                    signal_type=SignalType.SELL,
                    reason=f"[INVERTED] {signal.reason}",
                )
            elif signal.signal_type is SignalType.SELL:
                signal = replace(
                    signal,
                    signal_type=SignalType.BUY,
                    reason=f"[INVERTED] {signal.reason}",
                )

        if self.use_open_interest and signal.signal_type is not SignalType.HOLD:
            if not has_oi_evaluation(signal.reason):
                signal = strategy.apply_open_interest_confluence(
                    signal=signal,
                    candles=candles,
                    min_change_pct=self.min_oi_change_pct,
                    confidence_bonus=self.oi_confidence_bonus,
                    strict=self.require_oi_confluence,
                )

        if self.filter_funding_sentiment and signal.signal_type is not SignalType.HOLD:
            if not has_funding_evaluation(signal.reason):
                signal = strategy.apply_funding_sentiment_filter(
                    signal=signal,
                    candles=candles,
                    max_long_funding=self.max_long_funding_rate,
                    min_short_funding=self.min_short_funding_rate,
                    strict=self.require_funding_sentiment,
                )

        if self.filter_account_ratio and signal.signal_type is not SignalType.HOLD:
            if not has_account_ratio_evaluation(signal.reason):
                signal = strategy.apply_account_ratio_filter(
                    signal=signal,
                    candles=candles,
                    max_long_ratio=self.max_long_account_ratio,
                    min_short_ratio=self.min_short_account_ratio,
                    strict=self.require_account_ratio_confluence,
                    confirm_htf=self.confirm_htf_account_ratio,
                )

        return signal

    def get_minimum_candles(self, *, strategy_type: StrategyType) -> int:
        """Return the requirement for one explicit strategy type."""
        return self.strategy_resolver.resolve(
            strategy_type=strategy_type,
        ).minimum_candles
