"""
Botragram

Description:
    Trading signal generation engine.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Standard Library
# =============================================================================
from collections.abc import Sequence
from dataclasses import dataclass, replace

# =============================================================================
# Local Imports
# =============================================================================
from botragram.enums import SignalType, StrategyType
from botragram.models import Candle, Signal
from botragram.strategies.factory import StrategyResolver

__all__ = [
    "SignalEngine",
]


# =============================================================================
# Signal Engine
# =============================================================================
@dataclass(slots=True, kw_only=True, frozen=True)
class SignalEngine:
    """Generate signals from an explicit type resolved by an immutable registry."""

    strategy_resolver: StrategyResolver
    default_strategy_type: StrategyType
    invert_signals: bool = False

    def generate(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate a trading signal from market candles.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit strategy selection. Omitted only by legacy
                non-context callers, which use the immutable configured default.

        Returns:
            Signal generated by the resolved strategy, optionally inverted.

        Raises:
            ValueError: If candle data is invalid or insufficient.
        """
        resolved_strategy_type = (
            strategy_type if strategy_type is not None else self.default_strategy_type
        )
        raw_signal = self.strategy_resolver.resolve(
            strategy_type=resolved_strategy_type,
        ).generate_signal(
            candles=candles,
        )
        if not self.invert_signals:
            return raw_signal

        if raw_signal.signal_type is SignalType.BUY:
            return replace(
                raw_signal,
                signal_type=SignalType.SELL,
                reason=f"[INVERTED] {raw_signal.reason}",
            )
        if raw_signal.signal_type is SignalType.SELL:
            return replace(
                raw_signal,
                signal_type=SignalType.BUY,
                reason=f"[INVERTED] {raw_signal.reason}",
            )
        return raw_signal

    def get_minimum_candles(self, *, strategy_type: StrategyType) -> int:
        """Return the requirement for one explicit strategy type."""
        return self.strategy_resolver.resolve(
            strategy_type=strategy_type,
        ).minimum_candles
