"""
Botragram

Description:
    Trading signal generation engine.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Standard Library
# =============================================================================
from collections.abc import Sequence
from dataclasses import dataclass

# =============================================================================
# Local Imports
# =============================================================================
from botragram.models import Candle, Signal
from botragram.strategies.base import BaseStrategy

__all__ = [
    "SignalEngine",
]


# =============================================================================
# Signal Engine
# =============================================================================
@dataclass(
    slots=True,
    kw_only=True,
    frozen=True,
)
class SignalEngine:
    """Generate trading signals using the configured strategy."""

    strategy: BaseStrategy

    def generate(
        self,
        *,
        candles: Sequence[Candle],
    ) -> Signal:
        """Generate a trading signal from market candles.

        Args:
            candles: Candles ordered from oldest to newest.

        Returns:
            Signal generated by the configured strategy.

        Raises:
            ValueError: If candle data is invalid or insufficient.
        """
        return self.strategy.generate_signal(
            candles=candles,
        )
