"""
Botragram

Description:
    Constants package initialization.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Local Imports
# =============================================================================
from botragram.constants.ai import (
    DEFAULT_AI_MAX_TOKENS,
    DEFAULT_AI_MODEL,
    DEFAULT_AI_PROVIDER,
    DEFAULT_AI_TEMPERATURE,
    DEFAULT_AI_TIMEOUT,
)
from botragram.constants.app import APP_NAME, APP_VERSION, DEFAULT_ENCODING
from botragram.constants.env import (
    ENV_ACTIVE_EXCHANGE,
    ENV_AI_MODEL,
    ENV_AI_PROVIDER,
    ENV_AUTONOMOUS_EXECUTION_ENABLED,
    ENV_BINANCE_API_KEY,
    ENV_BINANCE_API_SECRET,
    ENV_BINANCE_MARKET_TYPE,
    ENV_BINANCE_TESTNET,
    ENV_BITGET_API_KEY,
    ENV_BITGET_API_SECRET,
    ENV_BITGET_PASSPHRASE,
    ENV_BITGET_TESTNET,
    ENV_BOTRAGRAM_PROFILE,
    ENV_BYBIT_API_KEY,
    ENV_BYBIT_API_SECRET,
    ENV_BYBIT_TESTNET,
    ENV_EXCHANGE_API_KEY_LEGACY,
    ENV_EXCHANGE_API_SECRET_LEGACY,
    ENV_EXECUTION_POLICY,
    ENV_GEMINI_API_KEY,
    ENV_LOG_LEVEL,
    ENV_LOG_LEVEL_LEGACY,
    ENV_OKX_API_KEY,
    ENV_OKX_API_SECRET,
    ENV_OKX_PASSPHRASE,
    ENV_OKX_TESTNET,
    ENV_OPENAI_API_KEY,
    ENV_OPENROUTER_API_KEY,
    ENV_TELEGRAM_CHAT_ID,
    ENV_TELEGRAM_TOKEN,
    ENV_TELEGRAM_TOKEN_LEGACY,
    ENV_TRADE_MODE,
    ENV_TRADE_MODE_LEGACY,
)
from botragram.constants.exchange import (
    BINANCE_FUTURES_REST_BASE_URL,
    BINANCE_FUTURES_TESTNET_REST_BASE_URL,
    BINANCE_FUTURES_TESTNET_WEBSOCKET_BASE_URL,
    BINANCE_FUTURES_WEBSOCKET_BASE_URL,
    BINANCE_REST_BASE_URL,
    BINANCE_TESTNET_REST_BASE_URL,
    BINANCE_TESTNET_WEBSOCKET_BASE_URL,
    BINANCE_WEBSOCKET_BASE_URL,
    DEFAULT_CANDLE_FETCH_LIMIT,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RECV_WINDOW_MS,
    DEFAULT_REQUEST_TIMEOUT_SECONDS,
    DEFAULT_RETRY_DELAY_SECONDS,
    DEFAULT_WS_RECONNECT_DELAY_SECONDS,
)
from botragram.constants.indicator import (
    DEFAULT_ADX_PERIOD,
    DEFAULT_ATR_PERIOD,
    DEFAULT_BBANDS_PERIOD,
    DEFAULT_BBANDS_STDDEV,
    DEFAULT_EMA_FAST_PERIOD,
    DEFAULT_EMA_SLOW_PERIOD,
    DEFAULT_MACD_FAST_PERIOD,
    DEFAULT_MACD_SIGNAL_PERIOD,
    DEFAULT_MACD_SLOW_PERIOD,
    DEFAULT_RSI_OVERBOUGHT,
    DEFAULT_RSI_OVERSOLD,
    DEFAULT_RSI_PERIOD,
    DEFAULT_SMA_PERIOD,
)
from botragram.constants.market import (
    DEFAULT_DISCOVERY_MAX_SYMBOLS,
    DEFAULT_DISCOVERY_TOP_N,
    DEFAULT_MAKER_FEE_RATE,
    DEFAULT_SLIPPAGE_RATE,
    DEFAULT_TAKER_FEE_RATE,
)
from botragram.constants.order import (
    DEFAULT_CLIENT_ORDER_ID_PREFIX,
    DEFAULT_ORDER_QUANTITY,
    DEFAULT_SLIPPAGE_TOLERANCE,
)
from botragram.constants.position import (
    DEFAULT_LEVERAGE,
    DEFAULT_STOP_LOSS_RATE,
    DEFAULT_TAKE_PROFIT_RATE,
    DEFAULT_TRAILING_STOP_RATE,
)
from botragram.constants.risk import (
    DEFAULT_MAX_ACCOUNT_EXPOSURE,
    DEFAULT_MAX_DAILY_LOSS,
    DEFAULT_MAX_OPEN_POSITIONS,
    DEFAULT_MIN_RISK_REWARD_RATIO,
    DEFAULT_RISK_PER_TRADE,
)
from botragram.constants.strategy import (
    DEFAULT_CONFIRMATION_CANDLES,
    DEFAULT_COOLDOWN_CANDLES,
    DEFAULT_MAX_SIGNAL_AGE,
    DEFAULT_MIN_SIGNAL_STRENGTH,
)
from botragram.constants.telegram import (
    CMD_POSITIONS,
    CMD_SETTINGS,
    CMD_START,
    CMD_STATUS,
    CMD_STOP,
    DEFAULT_MENU_COLUMNS,
    DEFAULT_PARSE_MODE,
    MENU_BALANCE,
    MENU_EXCHANGE,
    MENU_HISTORY,
    MENU_MARKET,
    MENU_ORDERS,
    MENU_PAUSE,
    MENU_POSITIONS,
    MENU_SETTINGS,
    MENU_START,
    MENU_STATUS,
    MENU_STOP,
    MENU_STRATEGY,
    MENU_STREAM,
    MENU_TEST,
)
from botragram.constants.time import (
    DISPLAY_DATETIME_FORMAT,
    HOURS_PER_DAY,
    ISO_DATETIME_FORMAT,
    MINUTES_PER_HOUR,
    SECONDS_PER_DAY,
    SECONDS_PER_HOUR,
    SECONDS_PER_MINUTE,
)

# =============================================================================
# Exports
# =============================================================================
__all__ = [
    # AI
    "DEFAULT_AI_MAX_TOKENS",
    "DEFAULT_AI_MODEL",
    "DEFAULT_AI_PROVIDER",
    "DEFAULT_AI_TEMPERATURE",
    "DEFAULT_AI_TIMEOUT",
    # Application
    "APP_NAME",
    "APP_VERSION",
    "DEFAULT_ENCODING",
    # Environment
    "ENV_ACTIVE_EXCHANGE",
    "ENV_AUTONOMOUS_EXECUTION_ENABLED",
    "ENV_EXECUTION_POLICY",
    "ENV_AI_MODEL",
    "ENV_AI_PROVIDER",
    "ENV_BINANCE_API_KEY",
    "ENV_BINANCE_API_SECRET",
    "ENV_BINANCE_MARKET_TYPE",
    "ENV_BINANCE_TESTNET",
    "ENV_BOTRAGRAM_PROFILE",
    "ENV_BITGET_API_KEY",
    "ENV_BITGET_API_SECRET",
    "ENV_BITGET_PASSPHRASE",
    "ENV_BITGET_TESTNET",
    "ENV_BYBIT_API_KEY",
    "ENV_BYBIT_API_SECRET",
    "ENV_BYBIT_TESTNET",
    "ENV_EXCHANGE_API_KEY_LEGACY",
    "ENV_EXCHANGE_API_SECRET_LEGACY",
    "ENV_GEMINI_API_KEY",
    "ENV_LOG_LEVEL",
    "ENV_LOG_LEVEL_LEGACY",
    "ENV_OKX_API_KEY",
    "ENV_OKX_API_SECRET",
    "ENV_OKX_PASSPHRASE",
    "ENV_OKX_TESTNET",
    "ENV_OPENAI_API_KEY",
    "ENV_OPENROUTER_API_KEY",
    "ENV_TELEGRAM_CHAT_ID",
    "ENV_TELEGRAM_TOKEN",
    "ENV_TELEGRAM_TOKEN_LEGACY",
    "ENV_TRADE_MODE",
    "ENV_TRADE_MODE_LEGACY",
    # Exchange
    "BINANCE_REST_BASE_URL",
    "BINANCE_FUTURES_REST_BASE_URL",
    "BINANCE_FUTURES_TESTNET_REST_BASE_URL",
    "BINANCE_FUTURES_TESTNET_WEBSOCKET_BASE_URL",
    "BINANCE_FUTURES_WEBSOCKET_BASE_URL",
    "BINANCE_TESTNET_REST_BASE_URL",
    "BINANCE_TESTNET_WEBSOCKET_BASE_URL",
    "BINANCE_WEBSOCKET_BASE_URL",
    "DEFAULT_CANDLE_FETCH_LIMIT",
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_RECV_WINDOW_MS",
    "DEFAULT_REQUEST_TIMEOUT_SECONDS",
    "DEFAULT_RETRY_DELAY_SECONDS",
    "DEFAULT_WS_RECONNECT_DELAY_SECONDS",
    # Indicators
    "DEFAULT_ADX_PERIOD",
    "DEFAULT_ATR_PERIOD",
    "DEFAULT_BBANDS_PERIOD",
    "DEFAULT_BBANDS_STDDEV",
    "DEFAULT_EMA_FAST_PERIOD",
    "DEFAULT_EMA_SLOW_PERIOD",
    "DEFAULT_MACD_FAST_PERIOD",
    "DEFAULT_MACD_SIGNAL_PERIOD",
    "DEFAULT_MACD_SLOW_PERIOD",
    "DEFAULT_RSI_OVERBOUGHT",
    "DEFAULT_RSI_OVERSOLD",
    "DEFAULT_RSI_PERIOD",
    "DEFAULT_SMA_PERIOD",
    # Market
    "DEFAULT_DISCOVERY_MAX_SYMBOLS",
    "DEFAULT_DISCOVERY_TOP_N",
    "DEFAULT_MAKER_FEE_RATE",
    "DEFAULT_SLIPPAGE_RATE",
    "DEFAULT_TAKER_FEE_RATE",
    # Orders
    "DEFAULT_CLIENT_ORDER_ID_PREFIX",
    "DEFAULT_ORDER_QUANTITY",
    "DEFAULT_SLIPPAGE_TOLERANCE",
    # Positions
    "DEFAULT_LEVERAGE",
    "DEFAULT_STOP_LOSS_RATE",
    "DEFAULT_TAKE_PROFIT_RATE",
    "DEFAULT_TRAILING_STOP_RATE",
    # Risk
    "DEFAULT_MAX_ACCOUNT_EXPOSURE",
    "DEFAULT_MAX_DAILY_LOSS",
    "DEFAULT_MAX_OPEN_POSITIONS",
    "DEFAULT_MIN_RISK_REWARD_RATIO",
    "DEFAULT_RISK_PER_TRADE",
    # Strategy
    "DEFAULT_CONFIRMATION_CANDLES",
    "DEFAULT_COOLDOWN_CANDLES",
    "DEFAULT_MAX_SIGNAL_AGE",
    "DEFAULT_MIN_SIGNAL_STRENGTH",
    # Telegram
    "CMD_POSITIONS",
    "CMD_SETTINGS",
    "CMD_START",
    "CMD_STATUS",
    "CMD_STOP",
    "DEFAULT_MENU_COLUMNS",
    "DEFAULT_PARSE_MODE",
    "MENU_BALANCE",
    "MENU_EXCHANGE",
    "MENU_HISTORY",
    "MENU_MARKET",
    "MENU_ORDERS",
    "MENU_PAUSE",
    "MENU_POSITIONS",
    "MENU_SETTINGS",
    "MENU_START",
    "MENU_STATUS",
    "MENU_STOP",
    "MENU_STRATEGY",
    "MENU_STREAM",
    "MENU_TEST",
    # Time
    "DISPLAY_DATETIME_FORMAT",
    "HOURS_PER_DAY",
    "ISO_DATETIME_FORMAT",
    "MINUTES_PER_HOUR",
    "SECONDS_PER_DAY",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_MINUTE",
]
