"""
Botragram

Description:
    Environment variable key constants.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

__all__ = [
    "ENV_OPENAI_API_KEY",
    "ENV_GEMINI_API_KEY",
    "ENV_OPENROUTER_API_KEY",
    "ENV_AI_PROVIDER",
    "ENV_AI_MODEL",
    "ENV_BASE_ASSET",
    "ENV_TELEGRAM_TOKEN",
    "ENV_TELEGRAM_TOKEN_LEGACY",
    "ENV_TELEGRAM_CHAT_ID",
    "ENV_TRADE_MODE",
    "ENV_AUTONOMOUS_EXECUTION_ENABLED",
    "ENV_AUTONOMOUS_LIVE_ENTRY_ENABLED",
    "ENV_AUTONOMOUS_MAINNET_ENTRY_ENABLED",
    "ENV_EXECUTION_POLICY",
    "ENV_STRATEGY_TYPE",
    "ENV_INVERT_SIGNALS",
    "ENV_MIN_SIGNAL_CONFIDENCE",
    "ENV_MTF_CONFIRMATION_ENABLED",
    "ENV_MTF_TIMEFRAME",
    "ENV_MTF_EMA_PERIOD",
    "ENV_LTF_CONFIRMATION_ENABLED",
    "ENV_LTF_TIMEFRAME",
    "ENV_LTF_CONFIRMATION_MODE",
    "ENV_LTF_EMA_PERIOD",
    "ENV_BTC_TREND_FILTER_ENABLED",
    "ENV_BTC_TREND_INTERVAL",
    "ENV_BTC_TREND_EMA_PERIOD",
    "ENV_BREAKEVEN_ROI_THRESHOLD",
    "ENV_BREAKEVEN_PROGRESS_THRESHOLD",
    "ENV_BREAKEVEN_FEE_BUFFER",
    "ENV_STEPPED_STOP_ENABLED",
    "ENV_STEPPED_STOP_THRESHOLDS",
    "ENV_STEPPED_STOP_LOCKED_LAG",
    "ENV_TRAILING_MODE",
    "ENV_TRAILING_SWING_TIMEFRAME",
    "ENV_TRAILING_SWING_WINDOW",
    "ENV_TRAILING_BUFFER_PCT",
    "ENV_PARTIAL_TP_ENABLED",
    "ENV_PARTIAL_TP_RATIO",
    "ENV_PARTIAL_TP_TRIGGER_PROGRESS",
    "ENV_ENABLE_EARLY_POSITION_EXIT",
    "ENV_EARLY_EXIT_MIN_CONFIDENCE",
    "ENV_EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL",
    "ENV_EARLY_EXIT_CHECK_EXHAUSTION",
    "ENV_EARLY_EXIT_CHECK_OPPOSITE_SIGNAL",
    "ENV_VOLATILITY_SIZING_ENABLED",
    "ENV_BASELINE_VOLATILITY_PCT",
    "ENV_DYNAMIC_SIZING_ENABLED",
    "ENV_CONFIDENCE_SIZING_ENABLED",
    "ENV_BASELINE_CONFIDENCE",
    "ENV_MAX_CONFIDENCE_MULTIPLIER",
    "ENV_DYNAMIC_LEVERAGE_ENABLED",
    "ENV_MIN_LEVERAGE",
    "ENV_MAX_LEVERAGE",
    "ENV_SLOT_SIZING_ENABLED",
    "ENV_SLOT_MARGIN_BUFFER_PCT",
    "ENV_MIN_ORDER_NOTIONAL_USDT",
    "ENV_DISCOVERY_FILTER_EXTREME_VOLATILITY",
    "ENV_DISCOVERY_FILTER_MIN_LIQUIDITY",
    "ENV_DISCOVERY_MAX_CANDLE_VOLATILITY_PCT",
    "ENV_DISCOVERY_MIN_24H_TURNOVER_USDT",
    "ENV_DISCOVERY_MIN_QUOTE_VOLUME_USDT",
    "ENV_DISCOVERY_USE_DYNAMIC_VOLUME",
    "ENV_DISCOVERY_VOLUME_SMA_PERIOD",
    "ENV_USE_OPEN_INTEREST",
    "ENV_MIN_OI_CHANGE_PCT",
    "ENV_REQUIRE_OI_CONFLUENCE",
    "ENV_FILTER_FUNDING_SENTIMENT",
    "ENV_MAX_LONG_FUNDING_RATE",
    "ENV_MIN_SHORT_FUNDING_RATE",
    "ENV_REQUIRE_FUNDING_SENTIMENT",
    "ENV_FILTER_ACCOUNT_RATIO",
    "ENV_MAX_LONG_ACCOUNT_RATIO",
    "ENV_MIN_SHORT_ACCOUNT_RATIO",
    "ENV_REQUIRE_ACCOUNT_RATIO_CONFLUENCE",
    "ENV_CONFIRM_HTF_ACCOUNT_RATIO",
    "ENV_ACCOUNT_RATIO_HTF_PERIOD",
    "ENV_LOG_LEVEL",
    "ENV_LOG_FILENAME",
    "ENV_SCALPING_STOP_LOSS_PCT",
    "ENV_SCALPING_TAKE_PROFIT_PCT",
    "ENV_TREND_STOP_LOSS_PCT",
    "ENV_TREND_TAKE_PROFIT_PCT",
    "ENV_SWING_STOP_LOSS_PCT",
    "ENV_SWING_TAKE_PROFIT_PCT",
    "ENV_STOP_LOSS_PCT",
    "ENV_TAKE_PROFIT_PCT",
    "ENV_EMA_CROSS_STOP_LOSS_PCT",
    "ENV_EMA_CROSS_TAKE_PROFIT_PCT",
    "ENV_EMA_SCALPING_STOP_LOSS_PCT",
    "ENV_EMA_SCALPING_TAKE_PROFIT_PCT",
    "ENV_PIER_STOP_LOSS_PCT",
    "ENV_PIER_TAKE_PROFIT_PCT",
    "ENV_PIER_TREND_PERIOD",
    "ENV_PIER_PULLBACK_PERIOD",
    "ENV_PIER_RSI_PERIOD",
    "ENV_PIER_RSI_LONG_MIN",
    "ENV_PIER_RSI_LONG_MAX",
    "ENV_PIER_RSI_SHORT_MIN",
    "ENV_PIER_RSI_SHORT_MAX",
    "ENV_PIER_VOLUME_PERIOD",
    "ENV_PIER_VOLUME_MULTIPLIER",
    "ENV_PIER_MIN_WICK_RATIO",
    "ENV_PIER_MAX_OPPOSITE_WICK_RATIO",
    "ENV_PIER_MIN_ENGULFING_BODY_RATIO",
    "ENV_PIER_ATR_PERIOD",
    "ENV_PIER_ATR_SL_MULTIPLIER",
    "ENV_PIER_RISK_REWARD_RATIO",
    "ENV_PIER_MIN_CONFIDENCE",
    "ENV_PIER_REQUIRE_KEY_LEVEL_LOCATION",
    "ENV_PIER_SWING_LOOKBACK",
    "ENV_PIER_REQUIRE_TREND_FILTER",
    "ENV_PIER_REQUIRE_HTF_EXTREME_ZONE",
    "ENV_PIER_HTF_EXTREME_BUFFER_ATR",
    "ENV_PIER_STRICT_EMA_SIDE_REJECTION",
    "ENV_PIER_STALKING_ENABLED",
    "ENV_PIER_STALKING_MAX_BARS",
    "ENV_PIER_STALKING_MAX_CANDIDATES",
    "ENV_PIER_STALKING_RETEST_RATIO",
    "ENV_PIER_MIN_NATR_THRESHOLD",
    "ENV_PIER_MIN_SL_DISTANCE_PCT",
    "ENV_PIER_LOCATION_TOLERANCE_PCT",
    "ENV_PIER_LOCATION_ATR_MULTIPLIER",
    "ENV_PIER_PULLBACK_PROXIMITY_PCT",
    "ENV_PIER_PULLBACK_ATR_MULTIPLIER",
    "ENV_PIER_PINBAR_MIN_RANGE_ATR",
    "ENV_PIER_ENGULFING_MIN_BODY_ATR",
    "ENV_PIER_REQUIRE_CONFIRMATION",
    "ENV_PIER_INCLUDE_STAR_PATTERNS",
    "ENV_PIER_USE_PARABOLIC_SAR",
    "ENV_PIER_USE_MACD",
    "ENV_PIER_MACD_FAST_PERIOD",
    "ENV_PIER_MACD_SLOW_PERIOD",
    "ENV_PIER_MACD_SIGNAL_PERIOD",
    "ENV_PIER_USE_STOCH_RSI",
    "ENV_PIER_STOCH_RSI_PERIOD",
    "ENV_PIER_STOCH_RSI_K_PERIOD",
    "ENV_PIER_STOCH_RSI_D_PERIOD",
    "ENV_PIER_STOCH_RSI_OVERBOUGHT",
    "ENV_PIER_STOCH_RSI_OVERSOLD",
    "ENV_PIER_USE_STRUCTURAL_TP",
    "ENV_PIER_STRUCTURAL_TP_BUFFER_PCT",
    "ENV_PIER_MIN_STRUCTURAL_RR",
    "ENV_PIER_BB_PERIOD",
    "ENV_PIER_BB_STD_DEV",
    "ENV_PIER_EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL",
    "ENV_PIER_EARLY_EXIT_CHECK_EXHAUSTION",
    "ENV_PIER_EARLY_EXIT_CHECK_OPPOSITE_SIGNAL",
    "ENV_PIER_EARLY_EXIT_MIN_CONFIDENCE",
    "ENV_PIER_ENABLE_EARLY_POSITION_EXIT",
    "ENV_PIER_HTF_BB_PERIOD",
    "ENV_PIER_HTF_BB_STD_DEV",
    "ENV_PIER_LEVERAGE",
    "ENV_PIER_MAX_POSITION_SIZE_USDT",
    "ENV_PIER_PARTIAL_TP_ENABLED",
    "ENV_PIER_PARTIAL_TP_RATIO",
    "ENV_PIER_PARTIAL_TP_TRIGGER_PROGRESS",
    "ENV_PIER_RISK_PER_TRADE_PCT",
    "ENV_PIER_TRAILING_BUFFER_PCT",
    "ENV_PIER_TRAILING_MODE",
    "ENV_PIER_TRAILING_SWING_WINDOW",
    "ENV_PIER_USE_HTF_STRUCTURAL_TP",
    "ENV_NY_RANGE_RISK_REWARD_RATIO",
    "ENV_NY_RANGE_MAX_SL_PCT",
    "ENV_NY_RANGE_MIN_SL_PCT",
    "ENV_NY_RANGE_FALLBACK_SL_PCT",
    "ENV_NY_RANGE_MAX_BREAKOUT_BARS",
    "ENV_NY_RANGE_MIN_CONFIDENCE",
    "ENV_NY_RANGE_BASE_CONFIDENCE",
    "ENV_NY_RANGE_USE_VOLUME_FILTER",
    "ENV_NY_RANGE_VOLUME_PERIOD",
    "ENV_NY_RANGE_VOLUME_MULTIPLIER",
    "ENV_NY_RANGE_VOLUME_CONFIDENCE_BONUS",
    "ENV_NY_RANGE_REQUIRE_VOLUME_CONFIRMATION",
    "ENV_NY_RANGE_REQUIRE_TREND_FILTER",
    "ENV_NY_RANGE_TREND_EMA_PERIOD",
    "ENV_NY_RANGE_USE_RSI_FILTER",
    "ENV_NY_RANGE_RSI_PERIOD",
    "ENV_NY_RANGE_RSI_LONG_MAX",
    "ENV_NY_RANGE_RSI_SHORT_MIN",
    "ENV_ORIGIN_RISK_REWARD_RATIO",
    "ENV_ORIGIN_STOP_LOSS_PCT",
    "ENV_ORIGIN_TAKE_PROFIT_PCT",
    "ENV_ORIGIN_MIN_SL_PCT",
    "ENV_ORIGIN_MAX_SL_PCT",
    "ENV_ORIGIN_FALLBACK_SL_PCT",
    "ENV_ORIGIN_MIN_CONFIDENCE",
    "ENV_ORIGIN_USE_TREND_FILTER",
    "ENV_ORIGIN_TREND_EMA_PERIOD",
    "ENV_ORIGIN_USE_VOLUME_FILTER",
    "ENV_ORIGIN_VOLUME_PERIOD",
    "ENV_ORIGIN_VOLUME_MULTIPLIER",
    "ENV_ORIGIN_USE_RSI_FILTER",
    "ENV_ORIGIN_RSI_PERIOD",
    "ENV_ORIGIN_RSI_LONG_MAX",
    "ENV_ORIGIN_RSI_SHORT_MIN",
    "ENV_ORIGIN_REQUIRE_RSI_DIRECTION",
    "ENV_ORIGIN_USE_BB_FILTER",
    "ENV_ORIGIN_BB_PERIOD",
    "ENV_ORIGIN_BB_STD_DEV",
    "ENV_ORIGIN_USE_MACD_FILTER",
    "ENV_ORIGIN_MACD_FAST_PERIOD",
    "ENV_ORIGIN_MACD_SLOW_PERIOD",
    "ENV_ORIGIN_MACD_SIGNAL_PERIOD",
    "ENV_ORIGIN_USE_PSAR_FILTER",
    "ENV_ORIGIN_PSAR_MAX_PROXIMITY_PCT",
    "ENV_BOTRAGRAM_INTERVAL",
    "ENV_ORIGIN_INTERVAL",
    "ENV_PIER_INTERVAL",
    "ENV_MORPH_INTERVAL",
    "ENV_CHOCH_INTERVAL",
    "ENV_CRBB_INTERVAL",
    "ENV_HCE_INTERVAL",
    "ENV_LSE_INTERVAL",
    "ENV_NY_RANGE_INTERVAL",
    "ENV_QUAD_INTERVAL",
    "ENV_SCALPING_INTERVAL",
    "ENV_TREND_INTERVAL",
    "ENV_SWING_INTERVAL",
    "ENV_MAX_OPEN_POSITIONS",
    "ENV_MAX_POSITION_SIZE_USDT",
    "ENV_RISK_PER_TRADE_PCT",
    "ENV_MAX_DRAWDOWN_PCT",
    "ENV_LEVERAGE",
    "ENV_MAX_EXECUTABLE_QUOTE_AGE_MS",
    "ENV_MAX_SPREAD_BPS",
    "ENV_GLOBAL_MARKET_INTERVAL",
    "ENV_MARKET_INTERVAL",
    "ENV_MARKET_SYMBOL",
    "ENV_SYMBOL",
    "ENV_QUOTE_ASSET",
    "ENV_CFD_SYMBOL",
    "ENV_FUTURES_SYMBOL",
    "ENV_SPOT_SYMBOL",
    "ENV_CFD_QUOTE_ASSET",
    "ENV_FUTURES_QUOTE_ASSET",
    "ENV_STRATEGY_TIMEFRAME_OVERRIDE_ENABLED",
    "ENV_STRATEGY_TIMEFRAME_OVERRIDE",
    "ENV_DISCOVERY_MAX_UNIVERSE_SYMBOLS",
    "ENV_DISCOVERY_UNIVERSE_LIMIT",
    "ENV_DISCOVERY_BATCH_SIZE",
    "ENV_DISCOVERY_CADENCE_SECONDS",
    "ENV_DISCOVERY_CANDLE_DELAY_SECONDS",
    "ENV_CANDLE_RETENTION_DAYS",
    "ENV_CANDLE_PRUNING_INTERVAL_HOURS",
    "ENV_BOTRAGRAM_PROFILE",
    "ENV_BOTRAGRAM_ENV_FILE",
    "ENV_ACTIVE_EXCHANGE",
    "ENV_BINANCE_API_KEY",
    "ENV_BINANCE_API_SECRET",
    "ENV_BINANCE_MARKET_TYPE",
    "ENV_BINANCE_TESTNET",
    "ENV_BITGET_API_KEY",
    "ENV_BITGET_API_SECRET",
    "ENV_BITGET_CFD_MODE",
    "ENV_BITGET_PASSPHRASE",
    "ENV_BITGET_TESTNET",
    "ENV_BITGET_MARKET_TYPE",
    "ENV_BITGET_MARGIN_MODE",
    "ENV_MARGIN_MODE",
    "ENV_BYBIT_API_KEY",
    "ENV_BYBIT_API_SECRET",
    "ENV_BYBIT_DEMO",
    "ENV_BYBIT_MARKET_TYPE",
    "ENV_BYBIT_TESTNET",
    "ENV_OKX_API_KEY",
    "ENV_OKX_API_SECRET",
    "ENV_OKX_PASSPHRASE",
    "ENV_OKX_TESTNET",
    "ENV_EXCHANGE_API_KEY_LEGACY",
    "ENV_EXCHANGE_API_SECRET_LEGACY",
    "ENV_TRADE_MODE_LEGACY",
    "ENV_LOG_LEVEL_LEGACY",
]

# =============================================================================
# Constants — AI
# =============================================================================
ENV_OPENAI_API_KEY: str = "OPENAI_API_KEY"
ENV_GEMINI_API_KEY: str = "GEMINI_API_KEY"
ENV_OPENROUTER_API_KEY: str = "OPENROUTER_API_KEY"
ENV_AI_PROVIDER: str = "AI_PROVIDER"
ENV_AI_MODEL: str = "AI_MODEL"

# =============================================================================
# Constants — Telegram
# =============================================================================
ENV_TELEGRAM_TOKEN: str = "TELEGRAM_TOKEN"
ENV_TELEGRAM_TOKEN_LEGACY: str = "BOTRAGRAM_TELEGRAM_TOKEN"
ENV_TELEGRAM_CHAT_ID: str = "TELEGRAM_CHAT_ID"

# =============================================================================
# Constants — Application Settings
# =============================================================================
ENV_TRADE_MODE: str = "TRADE_MODE"
ENV_AUTONOMOUS_EXECUTION_ENABLED: str = "AUTONOMOUS_EXECUTION_ENABLED"
ENV_AUTONOMOUS_LIVE_ENTRY_ENABLED: str = "AUTONOMOUS_LIVE_ENTRY_ENABLED"
ENV_AUTONOMOUS_MAINNET_ENTRY_ENABLED: str = "AUTONOMOUS_MAINNET_ENTRY_ENABLED"
ENV_EXECUTION_POLICY: str = "EXECUTION_POLICY"
ENV_STRATEGY_TYPE: str = "STRATEGY_TYPE"
ENV_INVERT_SIGNALS: str = "INVERT_SIGNALS"
ENV_MIN_SIGNAL_CONFIDENCE: str = "MIN_SIGNAL_CONFIDENCE"
ENV_MTF_CONFIRMATION_ENABLED: str = "MTF_CONFIRMATION_ENABLED"
ENV_MTF_TIMEFRAME: str = "MTF_TIMEFRAME"
ENV_MTF_EMA_PERIOD: str = "MTF_EMA_PERIOD"
ENV_LTF_CONFIRMATION_ENABLED: str = "LTF_CONFIRMATION_ENABLED"
ENV_LTF_TIMEFRAME: str = "LTF_TIMEFRAME"
ENV_LTF_CONFIRMATION_MODE: str = "LTF_CONFIRMATION_MODE"
ENV_LTF_EMA_PERIOD: str = "LTF_EMA_PERIOD"
ENV_BTC_TREND_FILTER_ENABLED: str = "BTC_TREND_FILTER_ENABLED"
ENV_BTC_TREND_INTERVAL: str = "BTC_TREND_INTERVAL"
ENV_BTC_TREND_EMA_PERIOD: str = "BTC_TREND_EMA_PERIOD"
ENV_BREAKEVEN_ROI_THRESHOLD: str = "BREAKEVEN_ROI_THRESHOLD"
ENV_BREAKEVEN_PROGRESS_THRESHOLD: str = "BREAKEVEN_PROGRESS_THRESHOLD"
ENV_BREAKEVEN_FEE_BUFFER: str = "BREAKEVEN_FEE_BUFFER"
ENV_STEPPED_STOP_ENABLED: str = "STEPPED_STOP_ENABLED"
ENV_STEPPED_STOP_THRESHOLDS: str = "STEPPED_STOP_THRESHOLDS"
ENV_STEPPED_STOP_LOCKED_LAG: str = "STEPPED_STOP_LOCKED_LAG"
ENV_TRAILING_MODE: str = "TRAILING_MODE"
ENV_TRAILING_SWING_TIMEFRAME: str = "TRAILING_SWING_TIMEFRAME"
ENV_TRAILING_SWING_WINDOW: str = "TRAILING_SWING_WINDOW"
ENV_TRAILING_BUFFER_PCT: str = "TRAILING_BUFFER_PCT"
ENV_PARTIAL_TP_ENABLED: str = "PARTIAL_TP_ENABLED"
ENV_PARTIAL_TP_RATIO: str = "PARTIAL_TP_RATIO"
ENV_PARTIAL_TP_TRIGGER_PROGRESS: str = "PARTIAL_TP_TRIGGER_PROGRESS"
ENV_ENABLE_EARLY_POSITION_EXIT: str = "ENABLE_EARLY_POSITION_EXIT"
ENV_EARLY_EXIT_MIN_CONFIDENCE: str = "EARLY_EXIT_MIN_CONFIDENCE"
ENV_EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL: str = "EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL"
ENV_EARLY_EXIT_CHECK_EXHAUSTION: str = "EARLY_EXIT_CHECK_EXHAUSTION"
ENV_EARLY_EXIT_CHECK_OPPOSITE_SIGNAL: str = "EARLY_EXIT_CHECK_OPPOSITE_SIGNAL"
ENV_VOLATILITY_SIZING_ENABLED: str = "VOLATILITY_SIZING_ENABLED"
ENV_BASELINE_VOLATILITY_PCT: str = "BASELINE_VOLATILITY_PCT"
ENV_DYNAMIC_SIZING_ENABLED: str = "DYNAMIC_SIZING_ENABLED"
ENV_CONFIDENCE_SIZING_ENABLED: str = "CONFIDENCE_SIZING_ENABLED"
ENV_BASELINE_CONFIDENCE: str = "BASELINE_CONFIDENCE"
ENV_MAX_CONFIDENCE_MULTIPLIER: str = "MAX_CONFIDENCE_MULTIPLIER"
ENV_DYNAMIC_LEVERAGE_ENABLED: str = "DYNAMIC_LEVERAGE_ENABLED"
ENV_MIN_LEVERAGE: str = "MIN_LEVERAGE"
ENV_MAX_LEVERAGE: str = "MAX_LEVERAGE"
ENV_SLOT_SIZING_ENABLED: str = "SLOT_SIZING_ENABLED"
ENV_SLOT_MARGIN_BUFFER_PCT: str = "SLOT_MARGIN_BUFFER_PCT"
ENV_MIN_ORDER_NOTIONAL_USDT: str = "MIN_ORDER_NOTIONAL_USDT"
ENV_DISCOVERY_FILTER_EXTREME_VOLATILITY: str = "DISCOVERY_FILTER_EXTREME_VOLATILITY"
ENV_DISCOVERY_MAX_CANDLE_VOLATILITY_PCT: str = "DISCOVERY_MAX_CANDLE_VOLATILITY_PCT"
ENV_DISCOVERY_FILTER_MIN_LIQUIDITY: str = "DISCOVERY_FILTER_MIN_LIQUIDITY"
ENV_DISCOVERY_MIN_QUOTE_VOLUME_USDT: str = "DISCOVERY_MIN_QUOTE_VOLUME_USDT"
ENV_DISCOVERY_USE_DYNAMIC_VOLUME: str = "DISCOVERY_USE_DYNAMIC_VOLUME"
ENV_DISCOVERY_VOLUME_SMA_PERIOD: str = "DISCOVERY_VOLUME_SMA_PERIOD"
ENV_DISCOVERY_MIN_24H_TURNOVER_USDT: str = "DISCOVERY_MIN_24H_TURNOVER_USDT"
ENV_USE_OPEN_INTEREST: str = "USE_OPEN_INTEREST"
ENV_MIN_OI_CHANGE_PCT: str = "MIN_OI_CHANGE_PCT"
ENV_REQUIRE_OI_CONFLUENCE: str = "REQUIRE_OI_CONFLUENCE"
ENV_FILTER_FUNDING_SENTIMENT: str = "FILTER_FUNDING_SENTIMENT"
ENV_MAX_LONG_FUNDING_RATE: str = "MAX_LONG_FUNDING_RATE"
ENV_MIN_SHORT_FUNDING_RATE: str = "MIN_SHORT_FUNDING_RATE"
ENV_REQUIRE_FUNDING_SENTIMENT: str = "REQUIRE_FUNDING_SENTIMENT"
ENV_FILTER_ACCOUNT_RATIO: str = "FILTER_ACCOUNT_RATIO"
ENV_MAX_LONG_ACCOUNT_RATIO: str = "MAX_LONG_ACCOUNT_RATIO"
ENV_MIN_SHORT_ACCOUNT_RATIO: str = "MIN_SHORT_ACCOUNT_RATIO"
ENV_REQUIRE_ACCOUNT_RATIO_CONFLUENCE: str = "REQUIRE_ACCOUNT_RATIO_CONFLUENCE"
ENV_CONFIRM_HTF_ACCOUNT_RATIO: str = "CONFIRM_HTF_ACCOUNT_RATIO"
ENV_ACCOUNT_RATIO_HTF_PERIOD: str = "ACCOUNT_RATIO_HTF_PERIOD"
ENV_LOG_LEVEL: str = "LOG_LEVEL"
ENV_LOG_FILENAME: str = "LOG_FILENAME"
ENV_BOTRAGRAM_PROFILE: str = "BOTRAGRAM_PROFILE"
ENV_BOTRAGRAM_ENV_FILE: str = "BOTRAGRAM_ENV_FILE"

# =============================================================================
# Constants — Risk
# =============================================================================
ENV_SCALPING_STOP_LOSS_PCT: str = "SCALPING_STOP_LOSS_PCT"
ENV_SCALPING_TAKE_PROFIT_PCT: str = "SCALPING_TAKE_PROFIT_PCT"
ENV_TREND_STOP_LOSS_PCT: str = "TREND_STOP_LOSS_PCT"
ENV_TREND_TAKE_PROFIT_PCT: str = "TREND_TAKE_PROFIT_PCT"
ENV_SWING_STOP_LOSS_PCT: str = "SWING_STOP_LOSS_PCT"
ENV_SWING_TAKE_PROFIT_PCT: str = "SWING_TAKE_PROFIT_PCT"
ENV_STOP_LOSS_PCT: str = "STOP_LOSS_PCT"
ENV_TAKE_PROFIT_PCT: str = "TAKE_PROFIT_PCT"
ENV_EMA_CROSS_STOP_LOSS_PCT: str = "EMA_CROSS_STOP_LOSS_PCT"
ENV_EMA_CROSS_TAKE_PROFIT_PCT: str = "EMA_CROSS_TAKE_PROFIT_PCT"
ENV_EMA_SCALPING_STOP_LOSS_PCT: str = "EMA_SCALPING_STOP_LOSS_PCT"
ENV_EMA_SCALPING_TAKE_PROFIT_PCT: str = "EMA_SCALPING_TAKE_PROFIT_PCT"
ENV_PIER_STOP_LOSS_PCT: str = "PIER_STOP_LOSS_PCT"
ENV_PIER_TAKE_PROFIT_PCT: str = "PIER_TAKE_PROFIT_PCT"
ENV_PIER_TREND_PERIOD: str = "PIER_TREND_PERIOD"
ENV_PIER_PULLBACK_PERIOD: str = "PIER_PULLBACK_PERIOD"
ENV_PIER_RSI_PERIOD: str = "PIER_RSI_PERIOD"
ENV_PIER_RSI_LONG_MIN: str = "PIER_RSI_LONG_MIN"
ENV_PIER_RSI_LONG_MAX: str = "PIER_RSI_LONG_MAX"
ENV_PIER_RSI_SHORT_MIN: str = "PIER_RSI_SHORT_MIN"
ENV_PIER_RSI_SHORT_MAX: str = "PIER_RSI_SHORT_MAX"
ENV_PIER_VOLUME_PERIOD: str = "PIER_VOLUME_PERIOD"
ENV_PIER_VOLUME_MULTIPLIER: str = "PIER_VOLUME_MULTIPLIER"
ENV_PIER_MIN_WICK_RATIO: str = "PIER_MIN_WICK_RATIO"
ENV_PIER_MAX_OPPOSITE_WICK_RATIO: str = "PIER_MAX_OPPOSITE_WICK_RATIO"
ENV_PIER_MIN_ENGULFING_BODY_RATIO: str = "PIER_MIN_ENGULFING_BODY_RATIO"
ENV_PIER_ATR_PERIOD: str = "PIER_ATR_PERIOD"
ENV_PIER_ATR_SL_MULTIPLIER: str = "PIER_ATR_SL_MULTIPLIER"
ENV_PIER_RISK_REWARD_RATIO: str = "PIER_RISK_REWARD_RATIO"
ENV_PIER_MIN_CONFIDENCE: str = "PIER_MIN_CONFIDENCE"
ENV_PIER_REQUIRE_KEY_LEVEL_LOCATION: str = "PIER_REQUIRE_KEY_LEVEL_LOCATION"
ENV_PIER_SWING_LOOKBACK: str = "PIER_SWING_LOOKBACK"
ENV_PIER_REQUIRE_TREND_FILTER: str = "PIER_REQUIRE_TREND_FILTER"
ENV_PIER_REQUIRE_HTF_EXTREME_ZONE: str = "PIER_REQUIRE_HTF_EXTREME_ZONE"
ENV_PIER_HTF_EXTREME_BUFFER_ATR: str = "PIER_HTF_EXTREME_BUFFER_ATR"
ENV_PIER_STRICT_EMA_SIDE_REJECTION: str = "PIER_STRICT_EMA_SIDE_REJECTION"
ENV_PIER_STALKING_ENABLED: str = "PIER_STALKING_ENABLED"
ENV_PIER_STALKING_MAX_BARS: str = "PIER_STALKING_MAX_BARS"
ENV_PIER_STALKING_MAX_CANDIDATES: str = "PIER_STALKING_MAX_CANDIDATES"
ENV_PIER_STALKING_RETEST_RATIO: str = "PIER_STALKING_RETEST_RATIO"
ENV_PIER_MIN_NATR_THRESHOLD: str = "PIER_MIN_NATR_THRESHOLD"
ENV_PIER_MIN_SL_DISTANCE_PCT: str = "PIER_MIN_SL_DISTANCE_PCT"
ENV_PIER_LOCATION_TOLERANCE_PCT: str = "PIER_LOCATION_TOLERANCE_PCT"
ENV_PIER_LOCATION_ATR_MULTIPLIER: str = "PIER_LOCATION_ATR_MULTIPLIER"
ENV_PIER_PULLBACK_PROXIMITY_PCT: str = "PIER_PULLBACK_PROXIMITY_PCT"
ENV_PIER_PULLBACK_ATR_MULTIPLIER: str = "PIER_PULLBACK_ATR_MULTIPLIER"
ENV_PIER_PINBAR_MIN_RANGE_ATR: str = "PIER_PINBAR_MIN_RANGE_ATR"
ENV_PIER_ENGULFING_MIN_BODY_ATR: str = "PIER_ENGULFING_MIN_BODY_ATR"
ENV_PIER_REQUIRE_CONFIRMATION: str = "PIER_REQUIRE_CONFIRMATION"
ENV_PIER_INCLUDE_STAR_PATTERNS: str = "PIER_INCLUDE_STAR_PATTERNS"
ENV_PIER_USE_PARABOLIC_SAR: str = "PIER_USE_PARABOLIC_SAR"
ENV_PIER_USE_MACD: str = "PIER_USE_MACD"
ENV_PIER_MACD_FAST_PERIOD: str = "PIER_MACD_FAST_PERIOD"
ENV_PIER_MACD_SLOW_PERIOD: str = "PIER_MACD_SLOW_PERIOD"
ENV_PIER_MACD_SIGNAL_PERIOD: str = "PIER_MACD_SIGNAL_PERIOD"
ENV_PIER_USE_STOCH_RSI: str = "PIER_USE_STOCH_RSI"
ENV_PIER_STOCH_RSI_PERIOD: str = "PIER_STOCH_RSI_PERIOD"
ENV_PIER_STOCH_RSI_K_PERIOD: str = "PIER_STOCH_RSI_K_PERIOD"
ENV_PIER_STOCH_RSI_D_PERIOD: str = "PIER_STOCH_RSI_D_PERIOD"
ENV_PIER_STOCH_RSI_OVERBOUGHT: str = "PIER_STOCH_RSI_OVERBOUGHT"
ENV_PIER_STOCH_RSI_OVERSOLD: str = "PIER_STOCH_RSI_OVERSOLD"
ENV_PIER_USE_STRUCTURAL_TP: str = "PIER_USE_STRUCTURAL_TP"
ENV_PIER_STRUCTURAL_TP_BUFFER_PCT: str = "PIER_STRUCTURAL_TP_BUFFER_PCT"
ENV_PIER_MIN_STRUCTURAL_RR: str = "PIER_MIN_STRUCTURAL_RR"
ENV_PIER_BB_PERIOD: str = "PIER_BB_PERIOD"
ENV_PIER_BB_STD_DEV: str = "PIER_BB_STD_DEV"
ENV_PIER_USE_HTF_STRUCTURAL_TP: str = "PIER_USE_HTF_STRUCTURAL_TP"
ENV_PIER_HTF_BB_PERIOD: str = "PIER_HTF_BB_PERIOD"
ENV_PIER_HTF_BB_STD_DEV: str = "PIER_HTF_BB_STD_DEV"
ENV_PIER_LEVERAGE: str = "PIER_LEVERAGE"
ENV_PIER_MAX_POSITION_SIZE_USDT: str = "PIER_MAX_POSITION_SIZE_USDT"
ENV_PIER_RISK_PER_TRADE_PCT: str = "PIER_RISK_PER_TRADE_PCT"
ENV_PIER_TRAILING_MODE: str = "PIER_TRAILING_MODE"
ENV_PIER_TRAILING_SWING_WINDOW: str = "PIER_TRAILING_SWING_WINDOW"
ENV_PIER_TRAILING_BUFFER_PCT: str = "PIER_TRAILING_BUFFER_PCT"
ENV_PIER_PARTIAL_TP_ENABLED: str = "PIER_PARTIAL_TP_ENABLED"
ENV_PIER_PARTIAL_TP_RATIO: str = "PIER_PARTIAL_TP_RATIO"
ENV_PIER_PARTIAL_TP_TRIGGER_PROGRESS: str = "PIER_PARTIAL_TP_TRIGGER_PROGRESS"
ENV_PIER_ENABLE_EARLY_POSITION_EXIT: str = "PIER_ENABLE_EARLY_POSITION_EXIT"
ENV_PIER_EARLY_EXIT_MIN_CONFIDENCE: str = "PIER_EARLY_EXIT_MIN_CONFIDENCE"
ENV_PIER_EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL: str = (
    "PIER_EARLY_EXIT_CHECK_CANDLESTICK_REVERSAL"
)
ENV_PIER_EARLY_EXIT_CHECK_OPPOSITE_SIGNAL: str = "PIER_EARLY_EXIT_CHECK_OPPOSITE_SIGNAL"
ENV_PIER_EARLY_EXIT_CHECK_EXHAUSTION: str = "PIER_EARLY_EXIT_CHECK_EXHAUSTION"
ENV_NY_RANGE_RISK_REWARD_RATIO: str = "NY_RANGE_RISK_REWARD_RATIO"
ENV_NY_RANGE_MAX_SL_PCT: str = "NY_RANGE_MAX_SL_PCT"
ENV_NY_RANGE_MIN_SL_PCT: str = "NY_RANGE_MIN_SL_PCT"
ENV_NY_RANGE_FALLBACK_SL_PCT: str = "NY_RANGE_FALLBACK_SL_PCT"
ENV_NY_RANGE_MAX_BREAKOUT_BARS: str = "NY_RANGE_MAX_BREAKOUT_BARS"
ENV_NY_RANGE_MIN_CONFIDENCE: str = "NY_RANGE_MIN_CONFIDENCE"
ENV_NY_RANGE_BASE_CONFIDENCE: str = "NY_RANGE_BASE_CONFIDENCE"
ENV_NY_RANGE_USE_VOLUME_FILTER: str = "NY_RANGE_USE_VOLUME_FILTER"
ENV_NY_RANGE_VOLUME_PERIOD: str = "NY_RANGE_VOLUME_PERIOD"
ENV_NY_RANGE_VOLUME_MULTIPLIER: str = "NY_RANGE_VOLUME_MULTIPLIER"
ENV_NY_RANGE_VOLUME_CONFIDENCE_BONUS: str = "NY_RANGE_VOLUME_CONFIDENCE_BONUS"
ENV_NY_RANGE_REQUIRE_VOLUME_CONFIRMATION: str = "NY_RANGE_REQUIRE_VOLUME_CONFIRMATION"
ENV_NY_RANGE_REQUIRE_TREND_FILTER: str = "NY_RANGE_REQUIRE_TREND_FILTER"
ENV_NY_RANGE_TREND_EMA_PERIOD: str = "NY_RANGE_TREND_EMA_PERIOD"
ENV_NY_RANGE_USE_RSI_FILTER: str = "NY_RANGE_USE_RSI_FILTER"
ENV_NY_RANGE_RSI_PERIOD: str = "NY_RANGE_RSI_PERIOD"
ENV_NY_RANGE_RSI_LONG_MAX: str = "NY_RANGE_RSI_LONG_MAX"
ENV_NY_RANGE_RSI_SHORT_MIN: str = "NY_RANGE_RSI_SHORT_MIN"
ENV_ORIGIN_RISK_REWARD_RATIO: str = "ORIGIN_RISK_REWARD_RATIO"
ENV_ORIGIN_STOP_LOSS_PCT: str = "ORIGIN_STOP_LOSS_PCT"
ENV_ORIGIN_TAKE_PROFIT_PCT: str = "ORIGIN_TAKE_PROFIT_PCT"
ENV_ORIGIN_MIN_SL_PCT: str = "ORIGIN_MIN_SL_PCT"
ENV_ORIGIN_MAX_SL_PCT: str = "ORIGIN_MAX_SL_PCT"
ENV_ORIGIN_FALLBACK_SL_PCT: str = "ORIGIN_FALLBACK_SL_PCT"
ENV_ORIGIN_MIN_CONFIDENCE: str = "ORIGIN_MIN_CONFIDENCE"
ENV_ORIGIN_USE_TREND_FILTER: str = "ORIGIN_USE_TREND_FILTER"
ENV_ORIGIN_TREND_EMA_PERIOD: str = "ORIGIN_TREND_EMA_PERIOD"
ENV_ORIGIN_USE_VOLUME_FILTER: str = "ORIGIN_USE_VOLUME_FILTER"
ENV_ORIGIN_VOLUME_PERIOD: str = "ORIGIN_VOLUME_PERIOD"
ENV_ORIGIN_VOLUME_MULTIPLIER: str = "ORIGIN_VOLUME_MULTIPLIER"
ENV_ORIGIN_USE_RSI_FILTER: str = "ORIGIN_USE_RSI_FILTER"
ENV_ORIGIN_RSI_PERIOD: str = "ORIGIN_RSI_PERIOD"
ENV_ORIGIN_RSI_LONG_MAX: str = "ORIGIN_RSI_LONG_MAX"
ENV_ORIGIN_RSI_SHORT_MIN: str = "ORIGIN_RSI_SHORT_MIN"
ENV_ORIGIN_REQUIRE_RSI_DIRECTION: str = "ORIGIN_REQUIRE_RSI_DIRECTION"
ENV_ORIGIN_USE_BB_FILTER: str = "ORIGIN_USE_BB_FILTER"
ENV_ORIGIN_BB_PERIOD: str = "ORIGIN_BB_PERIOD"
ENV_ORIGIN_BB_STD_DEV: str = "ORIGIN_BB_STD_DEV"
ENV_ORIGIN_USE_MACD_FILTER: str = "ORIGIN_USE_MACD_FILTER"
ENV_ORIGIN_MACD_FAST_PERIOD: str = "ORIGIN_MACD_FAST_PERIOD"
ENV_ORIGIN_MACD_SLOW_PERIOD: str = "ORIGIN_MACD_SLOW_PERIOD"
ENV_ORIGIN_MACD_SIGNAL_PERIOD: str = "ORIGIN_MACD_SIGNAL_PERIOD"
ENV_ORIGIN_USE_PSAR_FILTER: str = "ORIGIN_USE_PSAR_FILTER"
ENV_ORIGIN_PSAR_MAX_PROXIMITY_PCT: str = "ORIGIN_PSAR_MAX_PROXIMITY_PCT"
ENV_BOTRAGRAM_INTERVAL: str = "BOTRAGRAM_INTERVAL"
ENV_ORIGIN_INTERVAL: str = "ORIGIN_INTERVAL"
ENV_PIER_INTERVAL: str = "PIER_INTERVAL"
ENV_MORPH_INTERVAL: str = "MORPH_INTERVAL"
ENV_CHOCH_INTERVAL: str = "CHOCH_INTERVAL"
ENV_CRBB_INTERVAL: str = "CRBB_INTERVAL"
ENV_HCE_INTERVAL: str = "HCE_INTERVAL"
ENV_LSE_INTERVAL: str = "LSE_INTERVAL"
ENV_NY_RANGE_INTERVAL: str = "NY_RANGE_INTERVAL"
ENV_QUAD_INTERVAL: str = "QUAD_INTERVAL"
ENV_SCALPING_INTERVAL: str = "SCALPING_INTERVAL"
ENV_TREND_INTERVAL: str = "TREND_INTERVAL"
ENV_SWING_INTERVAL: str = "SWING_INTERVAL"
ENV_MAX_OPEN_POSITIONS: str = "MAX_OPEN_POSITIONS"
ENV_MAX_POSITION_SIZE_USDT: str = "MAX_POSITION_SIZE_USDT"
ENV_RISK_PER_TRADE_PCT: str = "RISK_PER_TRADE_PCT"
ENV_MAX_DRAWDOWN_PCT: str = "MAX_DRAWDOWN_PCT"
ENV_LEVERAGE: str = "LEVERAGE"
ENV_MAX_EXECUTABLE_QUOTE_AGE_MS: str = "MAX_EXECUTABLE_QUOTE_AGE_MS"
ENV_MAX_SPREAD_BPS: str = "MAX_SPREAD_BPS"
ENV_GLOBAL_MARKET_INTERVAL: str = "GLOBAL_MARKET_INTERVAL"
ENV_MARKET_INTERVAL: str = "MARKET_INTERVAL"
ENV_STRATEGY_TIMEFRAME_OVERRIDE_ENABLED: str = "STRATEGY_TIMEFRAME_OVERRIDE_ENABLED"
ENV_STRATEGY_TIMEFRAME_OVERRIDE: str = "STRATEGY_TIMEFRAME_OVERRIDE"
ENV_DISCOVERY_MAX_UNIVERSE_SYMBOLS: str = "DISCOVERY_MAX_UNIVERSE_SYMBOLS"
ENV_DISCOVERY_UNIVERSE_LIMIT: str = "DISCOVERY_UNIVERSE_LIMIT"
ENV_DISCOVERY_BATCH_SIZE: str = "DISCOVERY_BATCH_SIZE"
ENV_DISCOVERY_CADENCE_SECONDS: str = "DISCOVERY_CADENCE_SECONDS"
ENV_DISCOVERY_CANDLE_DELAY_SECONDS: str = "DISCOVERY_CANDLE_DELAY_SECONDS"
ENV_CANDLE_RETENTION_DAYS: str = "CANDLE_RETENTION_DAYS"
ENV_CANDLE_PRUNING_INTERVAL_HOURS: str = "CANDLE_PRUNING_INTERVAL_HOURS"

# =============================================================================
# Constants — Market Symbol and Assets
# =============================================================================
ENV_SYMBOL: str = "SYMBOL"
ENV_MARKET_SYMBOL: str = "MARKET_SYMBOL"
ENV_BASE_ASSET: str = "BASE_ASSET"
ENV_QUOTE_ASSET: str = "QUOTE_ASSET"
ENV_CFD_SYMBOL: str = "CFD_SYMBOL"
ENV_FUTURES_SYMBOL: str = "FUTURES_SYMBOL"
ENV_SPOT_SYMBOL: str = "SPOT_SYMBOL"
ENV_CFD_QUOTE_ASSET: str = "CFD_QUOTE_ASSET"
ENV_FUTURES_QUOTE_ASSET: str = "FUTURES_QUOTE_ASSET"

# =============================================================================
# Constants — Exchange
# =============================================================================
ENV_ACTIVE_EXCHANGE: str = "ACTIVE_EXCHANGE"

# =============================================================================
# Constants — Binance
# =============================================================================
ENV_BINANCE_API_KEY: str = "BINANCE_API_KEY"
ENV_BINANCE_API_SECRET: str = "BINANCE_API_SECRET"
ENV_BINANCE_MARKET_TYPE: str = "BINANCE_MARKET_TYPE"
ENV_BINANCE_TESTNET: str = "BINANCE_TESTNET"

# =============================================================================
# Constants — Bitget
# =============================================================================
ENV_BITGET_API_KEY: str = "BITGET_API_KEY"
ENV_BITGET_API_SECRET: str = "BITGET_API_SECRET"
ENV_BITGET_PASSPHRASE: str = "BITGET_PASSPHRASE"
ENV_BITGET_TESTNET: str = "BITGET_TESTNET"
ENV_BITGET_MARKET_TYPE: str = "BITGET_MARKET_TYPE"
ENV_BITGET_MARGIN_MODE: str = "BITGET_MARGIN_MODE"
ENV_BITGET_CFD_MODE: str = "BITGET_CFD_MODE"
ENV_MARGIN_MODE: str = "MARGIN_MODE"

# =============================================================================
# Constants — Bybit
# =============================================================================
ENV_BYBIT_API_KEY: str = "BYBIT_API_KEY"
ENV_BYBIT_API_SECRET: str = "BYBIT_API_SECRET"
ENV_BYBIT_DEMO: str = "BYBIT_DEMO"
ENV_BYBIT_MARKET_TYPE: str = "BYBIT_MARKET_TYPE"
ENV_BYBIT_TESTNET: str = "BYBIT_TESTNET"

# =============================================================================
# Constants — OKX
# =============================================================================
ENV_OKX_API_KEY: str = "OKX_API_KEY"
ENV_OKX_API_SECRET: str = "OKX_API_SECRET"
ENV_OKX_PASSPHRASE: str = "OKX_PASSPHRASE"
ENV_OKX_TESTNET: str = "OKX_TESTNET"

# =============================================================================
# Legacy fallback keys (kept for backward compatibility)
# =============================================================================
ENV_EXCHANGE_API_KEY_LEGACY: str = "BOTRAGRAM_EXCHANGE_API_KEY"
ENV_EXCHANGE_API_SECRET_LEGACY: str = "BOTRAGRAM_EXCHANGE_API_SECRET"
ENV_TRADE_MODE_LEGACY: str = "BOTRAGRAM_TRADE_MODE"
ENV_LOG_LEVEL_LEGACY: str = "BOTRAGRAM_LOG_LEVEL"
