"""
Botragram

Description:
    Trading strategy execution and signal persistence service.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Standard Library Imports
# =============================================================================
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime

# =============================================================================
# Local Imports
# =============================================================================
from botragram.engine import SignalEngine
from botragram.enums import SignalType, StrategyType
from botragram.models import Candle, Signal
from botragram.repositories import SignalRepository

__all__ = [
    "StrategyService",
]


# =============================================================================
# Service Classes
# =============================================================================
@dataclass(
    slots=True,
    kw_only=True,
    frozen=True,
)
class StrategyService:
    """Generate and persist trading signals."""

    signal_engine: SignalEngine
    signal_repository: SignalRepository

    def generate_signal(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate a trading signal from candle data.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit context strategy. Omitted only for existing
                non-context workflows using the configured default.

        Returns:
            Signal generated by the configured strategy.
        """
        return self.signal_engine.generate(
            candles=candles,
            strategy_type=strategy_type,
        )

    def get_minimum_candles(
        self,
        *,
        strategy_type: StrategyType | None = None,
    ) -> int:
        """Return the candle requirement for one explicit or default strategy."""
        resolved_type = (
            strategy_type
            if strategy_type is not None
            else self.signal_engine.default_strategy_type
        )
        return self.signal_engine.get_minimum_candles(
            strategy_type=resolved_type,
        )

    async def save_signal(
        self,
        *,
        signal: Signal,
    ) -> None:
        """Persist one already-generated trading signal.

        Args:
            signal: Trading signal that has passed caller-specific validation.
        """
        await self.signal_repository.save(
            signal=signal,
        )

    async def generate_and_save(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate and persist a trading signal.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit context strategy when one is available.

        Returns:
            Generated and persisted trading signal.
        """
        signal = self.generate_signal(
            candles=candles,
            strategy_type=strategy_type,
        )

        await self.save_signal(
            signal=signal,
        )

        return signal

    async def get_latest_signals(
        self,
        *,
        limit: int,
        symbol: str | None = None,
        signal_type: SignalType | None = None,
        strategy_name: str | None = None,
    ) -> Sequence[Signal]:
        """Return the latest persisted trading signals.

        Args:
            limit: Maximum number of signals to return.
            symbol: Optional trading symbol filter.
            signal_type: Optional signal-type filter.
            strategy_name: Optional strategy-name filter.

        Returns:
            Matching signals ordered from oldest to newest.

        Raises:
            ValueError: If the requested limit is invalid.
        """
        if limit <= 0:
            raise ValueError("Signal limit must be greater than zero")

        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_latest(
            limit=limit,
            symbol=normalized_symbol,
            signal_type=signal_type,
            strategy_name=normalized_strategy_name,
        )

    async def get_signals_between(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        symbol: str | None = None,
        signal_type: SignalType | None = None,
        strategy_name: str | None = None,
    ) -> Sequence[Signal]:
        """Return persisted signals generated within a datetime range.

        Args:
            start_time: Inclusive generation-time boundary.
            end_time: Inclusive generation-time boundary.
            symbol: Optional trading symbol filter.
            signal_type: Optional signal-type filter.
            strategy_name: Optional strategy-name filter.

        Returns:
            Matching signals ordered from oldest to newest.

        Raises:
            ValueError: If the datetime range is invalid.
        """
        if start_time > end_time:
            raise ValueError("Signal start time must not be after end time")

        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_between(
            start_time=start_time,
            end_time=end_time,
            symbol=normalized_symbol,
            signal_type=signal_type,
            strategy_name=normalized_strategy_name,
        )

    async def get_latest_signal(
        self,
        *,
        symbol: str,
        strategy_name: str | None = None,
    ) -> Signal | None:
        """Return the latest signal for a trading symbol.

        Args:
            symbol: Trading pair symbol.
            strategy_name: Optional strategy-name filter.

        Returns:
            Latest matching signal, or None when none exists.
        """
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_latest_for_symbol(
            symbol=self._normalize_symbol(symbol),
            strategy_name=normalized_strategy_name,
        )

    async def delete_old_signals(
        self,
        *,
        before: datetime,
        symbol: str | None = None,
    ) -> int:
        """Delete signals older than a datetime boundary.

        Args:
            before: Exclusive deletion boundary.
            symbol: Optional trading symbol filter.

        Returns:
            Number of deleted signal records.
        """
        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )

        return await self.signal_repository.delete_before(
            before=before,
            symbol=normalized_symbol,
        )

    @staticmethod
    def _normalize_symbol(
        symbol: str,
    ) -> str:
        """Normalize and validate a trading symbol."""
        normalized_symbol = symbol.strip().upper()

        if not normalized_symbol:
            raise ValueError("Trading symbol must not be empty")

        return normalized_symbol

    @staticmethod
    def _normalize_strategy_name(
        strategy_name: str,
    ) -> str:
        """Normalize and validate a strategy name."""
        normalized_strategy_name = strategy_name.strip()

        if not normalized_strategy_name:
            raise ValueError("Strategy name must not be empty")

        return normalized_strategy_name
