"""
Botragram

Description:
    Trading strategy execution and signal persistence service.

Python:
    3.14+
"""

# =============================================================================
# Future
# =============================================================================
from __future__ import annotations

# =============================================================================
# Standard Library Imports
# =============================================================================
from collections.abc import Sequence
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Protocol

# =============================================================================
# Local Imports
# =============================================================================
from botragram.engine import SignalEngine
from botragram.enums import SignalType, StalkingStatus, StrategyType
from botragram.models import Candle, Signal
from botragram.models.stalking import StalkingFunnelReport, StalkingSetup
from botragram.repositories import SignalRepository

__all__ = [
    "StrategyService",
    "StrategyStalkingProvider",
]


# =============================================================================
# Protocols
# =============================================================================
class StrategyStalkingProvider(Protocol):
    """Provide stalking candidate registration and bar evaluation."""

    def get_setup(self, symbol: str) -> StalkingSetup | None:
        """Return the current setup for a symbol, if any."""
        ...

    def register_candidate(
        self,
        *,
        signal: Signal,
        setup_candle: Candle,
        htf_zone_label: str = "HTF Extreme",
        max_bars: int | None = None,
        retest_ratio: Decimal | None = None,
        reversal_confirmed: bool | None = None,
    ) -> StalkingSetup | None:
        """Register a new candidate setup for stalking."""
        ...

    def on_candle_update(
        self,
        candle: Candle,
        prev_candle: Candle | None = None,
    ) -> StalkingSetup | None:
        """Evaluate a closed candle against active setup."""
        ...

    def build_triggered_signal(
        self,
        *,
        setup: StalkingSetup,
        trigger_candle: Candle,
    ) -> Signal:
        """Build an actionable entry Signal from a TRIGGERED stalking setup."""
        ...

    def record_scan(self, count: int = 1) -> None:
        """Record scanned candle count for telemetry funnel."""
        ...

    def record_zone_candidate(self, count: int = 1) -> None:
        """Record detected zone candidate count for telemetry funnel."""
        ...

    def record_rejection(self, reason: str, count: int = 1) -> None:
        """Record candidate rejection reason for telemetry funnel."""
        ...

    def get_funnel_report(self) -> StalkingFunnelReport:
        """Return a telemetry report of the stalking funnel."""
        ...


# =============================================================================
# Service Classes
# =============================================================================
@dataclass(
    slots=True,
    kw_only=True,
    frozen=True,
)
class StrategyService:
    """Generate and persist trading signals."""

    signal_engine: SignalEngine
    signal_repository: SignalRepository
    setup_stalking_service: StrategyStalkingProvider | None = None
    stalking_enabled: bool = False

    def generate_signal(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate a trading signal from candle data.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit context strategy. Omitted only for existing
                non-context workflows using the configured default.

        Returns:
            Signal generated by the configured strategy.
        """
        resolved_type = (
            strategy_type
            if strategy_type is not None
            else self.signal_engine.default_strategy_type
        )
        is_pier = resolved_type is StrategyType.PINBAR_ENGULFING_EMA_RSI
        stalking_svc = self.setup_stalking_service

        if not candles:
            return self.signal_engine.generate(
                candles=candles,
                strategy_type=strategy_type,
            )

        latest_candle = candles[-1]
        symbol = latest_candle.symbol

        # 1. Active Stalking State: Check if this symbol is currently in STALKING
        if self.stalking_enabled and stalking_svc is not None and is_pier:
            existing = stalking_svc.get_setup(symbol)
            if existing is not None:
                if existing.status is StalkingStatus.STALKING:
                    prev_c = candles[-2] if len(candles) >= 2 else None
                    updated = stalking_svc.on_candle_update(
                        latest_candle,
                        prev_candle=prev_c,
                    )
                    if (
                        updated is not None
                        and updated.status is StalkingStatus.TRIGGERED
                    ):
                        return stalking_svc.build_triggered_signal(
                            setup=updated,
                            trigger_candle=latest_candle,
                        )
                    # Still stalking, invalidated, or expired -> hold immediate entry
                    if (
                        updated is not None
                        and updated.status is StalkingStatus.STALKING
                    ):
                        if updated.reversal_confirmed:
                            reason_status = (
                                f"[STALKING] bar "
                                f"{updated.current_bar}/{existing.max_bars} "
                                f"reversal confirmed, awaiting retest@"
                                f"{updated.target_retest_price}"
                            )
                        else:
                            reason_status = (
                                f"[STALKING] bar "
                                f"{updated.current_bar}/{existing.max_bars} "
                                f"awaiting reversal in {updated.htf_zone_label}"
                            )
                    elif updated is not None:
                        reason_status = (
                            f"[STALKING_{updated.status.value.upper()}] bar "
                            f"{updated.current_bar}/{existing.max_bars}"
                        )
                    else:
                        reason_status = "[STALKING_INACTIVE]"

                    return Signal(
                        symbol=symbol,
                        signal_type=SignalType.HOLD,
                        price=latest_candle.close_price,
                        confidence=Decimal("0"),
                        strategy_name=resolved_type.value,
                        generated_at=latest_candle.close_time,
                        reason=reason_status,
                    )
                if (
                    existing.last_processed_candle_close_time is not None
                    and latest_candle.close_time
                    <= existing.last_processed_candle_close_time
                ):
                    return Signal(
                        symbol=symbol,
                        signal_type=SignalType.HOLD,
                        price=latest_candle.close_price,
                        confidence=Decimal("0"),
                        strategy_name=resolved_type.value,
                        generated_at=latest_candle.close_time,
                        reason=(
                            f"[STALKING_{existing.status.value.upper()}_PROCESSED] "
                            f"Candle already evaluated for "
                            f"{existing.status.value} setup"
                        ),
                    )

            # Stage 1 — Zone Candidate / Stalking Registration
            stalking_svc.record_scan()
            candidate_signal, rejection_reason = (
                self.signal_engine.detect_zone_candidate_detailed(
                    candles=candles,
                    strategy_type=strategy_type,
                )
            )
            if candidate_signal is None:
                raw_sig = self.signal_engine.generate(
                    candles=candles,
                    strategy_type=strategy_type,
                )
                if raw_sig.signal_type in {SignalType.BUY, SignalType.SELL}:
                    candidate_signal = raw_sig

            if candidate_signal is not None:
                stalking_svc.record_zone_candidate()
                reason_text = candidate_signal.reason or ""
                if candidate_signal.signal_type is SignalType.BUY:
                    side_str = "LONG"
                elif candidate_signal.signal_type is SignalType.SELL:
                    side_str = "SHORT"
                elif "[STALKING_ZONE_SHORT]" in reason_text:
                    side_str = "SHORT"
                else:
                    side_str = "LONG"

                registered = stalking_svc.register_candidate(
                    signal=candidate_signal,
                    setup_candle=latest_candle,
                    htf_zone_label=f"HTF Extreme {side_str}",
                )
                reason_header = (
                    f"[STALKING_REGISTERED] [STALKING_ZONE_{side_str}]"
                    if "[STALKING_ZONE" in reason_text
                    else "[STALKING_REGISTERED]"
                )
                if registered is not None:
                    return Signal(
                        symbol=symbol,
                        signal_type=SignalType.HOLD,
                        price=latest_candle.close_price,
                        confidence=candidate_signal.confidence,
                        strategy_name=resolved_type.value,
                        generated_at=latest_candle.close_time,
                        reason=(
                            f"{reason_header} {reason_text} - "
                            f"registered stalking: observing reversal/retest "
                            f"(invalidation={registered.invalidation_price})"
                        ),
                        stop_loss=candidate_signal.stop_loss,
                        take_profit=candidate_signal.take_profit,
                    )
                return Signal(
                    symbol=symbol,
                    signal_type=SignalType.HOLD,
                    price=latest_candle.close_price,
                    confidence=Decimal("0"),
                    strategy_name=resolved_type.value,
                    generated_at=latest_candle.close_time,
                    reason=(
                        f"[STALKING_CAPACITY_FULL] Setup stalking capacity reached; "
                        f"skipping candidate for {symbol}"
                    ),
                )
            else:
                stalking_svc.record_rejection(
                    reason=rejection_reason or "Filter rejected"
                )

            # Stalking active for PIER: Direct immediate BUY/SELL is prohibited
            return Signal(
                symbol=symbol,
                signal_type=SignalType.HOLD,
                price=latest_candle.close_price,
                confidence=Decimal("0"),
                strategy_name=resolved_type.value,
                generated_at=latest_candle.close_time,
                reason="[STALKING_IDLE] Awaiting PIER zone candidate setup",
            )

        # 2. Evaluate strategy normally (stalking disabled or non-PIER)
        return self.signal_engine.generate(
            candles=candles,
            strategy_type=strategy_type,
        )

    def get_minimum_candles(
        self,
        *,
        strategy_type: StrategyType | None = None,
    ) -> int:
        """Return the candle requirement for one explicit or default strategy."""
        resolved_type = (
            strategy_type
            if strategy_type is not None
            else self.signal_engine.default_strategy_type
        )
        return self.signal_engine.get_minimum_candles(
            strategy_type=resolved_type,
        )

    async def save_signal(
        self,
        *,
        signal: Signal,
    ) -> None:
        """Persist one already-generated trading signal.

        Args:
            signal: Trading signal that has passed caller-specific validation.
        """
        await self.signal_repository.save(
            signal=signal,
        )

    async def generate_and_save(
        self,
        *,
        candles: Sequence[Candle],
        strategy_type: StrategyType | None = None,
    ) -> Signal:
        """Generate and persist a trading signal.

        Args:
            candles: Candles ordered from oldest to newest.
            strategy_type: Explicit context strategy when one is available.

        Returns:
            Generated and persisted trading signal.
        """
        signal = self.generate_signal(
            candles=candles,
            strategy_type=strategy_type,
        )

        await self.save_signal(
            signal=signal,
        )

        return signal

    async def get_latest_signals(
        self,
        *,
        limit: int,
        symbol: str | None = None,
        signal_type: SignalType | None = None,
        strategy_name: str | None = None,
    ) -> Sequence[Signal]:
        """Return the latest persisted trading signals.

        Args:
            limit: Maximum number of signals to return.
            symbol: Optional trading symbol filter.
            signal_type: Optional signal-type filter.
            strategy_name: Optional strategy-name filter.

        Returns:
            Matching signals ordered from oldest to newest.

        Raises:
            ValueError: If the requested limit is invalid.
        """
        if limit <= 0:
            raise ValueError("Signal limit must be greater than zero")

        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_latest(
            limit=limit,
            symbol=normalized_symbol,
            signal_type=signal_type,
            strategy_name=normalized_strategy_name,
        )

    async def get_signals_between(
        self,
        *,
        start_time: datetime,
        end_time: datetime,
        symbol: str | None = None,
        signal_type: SignalType | None = None,
        strategy_name: str | None = None,
    ) -> Sequence[Signal]:
        """Return persisted signals generated within a datetime range.

        Args:
            start_time: Inclusive generation-time boundary.
            end_time: Inclusive generation-time boundary.
            symbol: Optional trading symbol filter.
            signal_type: Optional signal-type filter.
            strategy_name: Optional strategy-name filter.

        Returns:
            Matching signals ordered from oldest to newest.

        Raises:
            ValueError: If the datetime range is invalid.
        """
        if start_time > end_time:
            raise ValueError("Signal start time must not be after end time")

        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_between(
            start_time=start_time,
            end_time=end_time,
            symbol=normalized_symbol,
            signal_type=signal_type,
            strategy_name=normalized_strategy_name,
        )

    async def get_latest_signal(
        self,
        *,
        symbol: str,
        strategy_name: str | None = None,
    ) -> Signal | None:
        """Return the latest signal for a trading symbol.

        Args:
            symbol: Trading pair symbol.
            strategy_name: Optional strategy-name filter.

        Returns:
            Latest matching signal, or None when none exists.
        """
        normalized_strategy_name = (
            self._normalize_strategy_name(strategy_name)
            if strategy_name is not None
            else None
        )

        return await self.signal_repository.get_latest_for_symbol(
            symbol=self._normalize_symbol(symbol),
            strategy_name=normalized_strategy_name,
        )

    async def delete_old_signals(
        self,
        *,
        before: datetime,
        symbol: str | None = None,
    ) -> int:
        """Delete signals older than a datetime boundary.

        Args:
            before: Exclusive deletion boundary.
            symbol: Optional trading symbol filter.

        Returns:
            Number of deleted signal records.
        """
        normalized_symbol = (
            self._normalize_symbol(symbol) if symbol is not None else None
        )

        return await self.signal_repository.delete_before(
            before=before,
            symbol=normalized_symbol,
        )

    @staticmethod
    def _normalize_symbol(
        symbol: str,
    ) -> str:
        """Normalize and validate a trading symbol."""
        normalized_symbol = symbol.strip().upper()

        if not normalized_symbol:
            raise ValueError("Trading symbol must not be empty")

        return normalized_symbol

    @staticmethod
    def _normalize_strategy_name(
        strategy_name: str,
    ) -> str:
        """Normalize and validate a strategy name."""
        normalized_strategy_name = strategy_name.strip()

        if not normalized_strategy_name:
            raise ValueError("Strategy name must not be empty")

        return normalized_strategy_name

    def get_stalking_funnel_report(self) -> StalkingFunnelReport | None:
        """Return the stalking telemetry funnel report if stalking is enabled."""
        if self.setup_stalking_service is not None:
            return self.setup_stalking_service.get_funnel_report()
        return None
